-- This file has been generated by Ion. Do not edit.
return {
    [0] = {
        ["type"] = "WRootWin",
        ["name"] = "WRootWin",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS",
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1080,
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1920,
                            ["h"] = 1080,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1067,
                            ["tl"] = {
                                ["tls"] = 667,
                                ["tl"] = {
                                    ["tls"] = 534,
                                    ["tl"] = {
                                        ["regparams"] = {
                                            ["mode"] = 2,
                                            ["type"] = "WFrame",
                                            ["name"] = "Shells",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WGroupCW",
                                                    ["name"] = "WGroupCW<1>",
                                                    ["geom"] = {
                                                        ["y"] = 1,
                                                        ["x"] = 1,
                                                        ["w"] = 665,
                                                        ["h"] = 532,
                                                    },
                                                    ["switchto"] = true,
                                                    ["sizepolicy"] = "full",
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["type"] = "WClientWin",
                                                            ["bottom"] = true,
                                                            ["windowid"] = 18874378,
                                                            ["checkcode"] = 1,
                                                            ["sizepolicy"] = "full",
                                                            ["geom"] = {
                                                                ["y"] = 0,
                                                                ["x"] = 1,
                                                                ["w"] = 662,
                                                                ["h"] = 532,
                                                            },
                                                            ["level"] = 1,
                                                        },
                                                    },
                                                    ["level"] = 0,
                                                },
                                            },
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["dir"] = "vertical",
                                    ["brs"] = 533,
                                    ["br"] = {
                                        ["regparams"] = {
                                            ["mode"] = 2,
                                            ["type"] = "WFrame",
                                            ["name"] = "Code",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WGroupCW",
                                                    ["name"] = "WGroupCW<2>",
                                                    ["geom"] = {
                                                        ["y"] = 1,
                                                        ["x"] = 1,
                                                        ["w"] = 665,
                                                        ["h"] = 531,
                                                    },
                                                    ["switchto"] = true,
                                                    ["sizepolicy"] = "full",
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["type"] = "WClientWin",
                                                            ["bottom"] = true,
                                                            ["windowid"] = 8388642,
                                                            ["checkcode"] = 2,
                                                            ["sizepolicy"] = "full",
                                                            ["geom"] = {
                                                                ["y"] = 7,
                                                                ["x"] = 1,
                                                                ["w"] = 662,
                                                                ["h"] = 516,
                                                            },
                                                            ["level"] = 1,
                                                        },
                                                    },
                                                    ["level"] = 0,
                                                },
                                            },
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["type"] = "WSplitSplit",
                                },
                                ["dir"] = "horizontal",
                                ["brs"] = 1253,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["type"] = "WFrame",
                                        ["name"] = "Browser",
                                        ["saved_h"] = 1067,
                                        ["mode"] = 1,
                                        ["managed"] = {
                                        },
                                        ["saved_y"] = 0,
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 13,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [2] = {
                ["level"] = 1,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*",
                ["pseudomodal"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1080,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                },
                ["unnumbered"] = true,
            },
            [3] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free_glue",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "example_sp",
                ["hidden"] = true,
                ["mode"] = 0,
                ["geom"] = {
                    ["y"] = 40,
                    ["x"] = 160,
                    ["w"] = 1600,
                    ["h"] = 1000,
                },
                ["level"] = 1,
            },
            [4] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free_glue",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WGroupWS",
                        ["name"] = "WGroupWS<1>",
                        ["geom"] = {
                            ["y"] = 1,
                            ["x"] = 1,
                            ["w"] = 1598,
                            ["h"] = 998,
                        },
                        ["switchto"] = true,
                        ["sizepolicy"] = "full",
                        ["managed"] = {
                            [1] = {
                                ["type"] = "WFrame",
                                ["name"] = "WFrame<1>",
                                ["geom"] = {
                                    ["y"] = -1,
                                    ["x"] = -1,
                                    ["w"] = 671,
                                    ["h"] = 819,
                                },
                                ["level"] = 1,
                                ["mode"] = 3,
                                ["managed"] = {
                                    [1] = {
                                        ["type"] = "WGroupCW",
                                        ["name"] = "WGroupCW",
                                        ["geom"] = {
                                            ["y"] = 14,
                                            ["x"] = 1,
                                            ["w"] = 669,
                                            ["h"] = 804,
                                        },
                                        ["switchto"] = true,
                                        ["sizepolicy"] = "full",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WClientWin",
                                                ["bottom"] = true,
                                                ["windowid"] = 8388618,
                                                ["checkcode"] = 3,
                                                ["sizepolicy"] = "full",
                                                ["geom"] = {
                                                    ["y"] = 0,
                                                    ["x"] = 0,
                                                    ["w"] = 669,
                                                    ["h"] = 804,
                                                },
                                                ["level"] = 1,
                                            },
                                        },
                                        ["level"] = 0,
                                    },
                                },
                                ["sizepolicy"] = "visibility_constrained",
                            },
                        },
                        ["level"] = 0,
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "Scratch",
                ["hidden"] = true,
                ["mode"] = 2,
                ["geom"] = {
                    ["y"] = 40,
                    ["x"] = 160,
                    ["w"] = 1600,
                    ["h"] = 1000,
                },
                ["level"] = 1,
            },
        },
    },
}

